version: '3.9'

services:

  nginx:
    build: requirements/nginx
    image: nginx
    container_name: nginx
    depends_on:
      - mariadb
      - wordpress
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - WordPress:${NGINX_SERVED_FILES_PATH}
    ports:
      - "443:443"
    networks:
      - inception
    

  wordpress:
    build:
      context: requirements/wordpress
      args:
        - SERVED_PATH=${WORDPRESS_SERVED_FILES_PATH}
    image: wordpress
    container_name: wordpress
    restart: unless-stopped
    depends_on:
      - mariadb
    env_file:
      - .env
    volumes:
      - WordPress:${WORDPRESS_SERVED_FILES_PATH}
    networks:
      - inception

  mariadb:
    build: requirements/mariadb
    image: mariadb
    container_name: mariadb
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - DB:${MYSQL_DB_PATH}
    networks:
      - inception


networks:
  inception:
    name: inception

volumes:
  DB:
    name: DB
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: ${VOLUME_DB_PATH}
  WordPress:
    name: WordPress
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: ${VOLUME_WORDPRESS_PATH}

