version: '3.9'

services:

  nginx:
    build: requirements/nginx
    image: nginx
    container_name: nginx
    restart: always
    env_file:
      - .env
    volumes:
      - WordPress:${NGINX_SERVED_FILES_PATH}
    ports:
      - "443:443"
    networks:
      - inception
    

  wordpress:
    build: requirements/wordpress
    image: wordpress
    container_name: wordpress
    restart: always
    env_file:
      - .env
    volumes:
      - WordPress:${WORDPRESS_SERVED_FILES_PATH}
    networks:
      - inception
    expose:
      - 9000

  mariadb:
    build: requirements/mariadb
    image: mariadb
    container_name: mariadb
    restart: always
    env_file:
      - .env
    volumes:
      - DB:${MYSQL_DB_PATH}
    networks:
      - inception


networks:
  inception:
    name: inception

volumes:
  DB:
    name: DB
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: ${VOLUME_DB_PATH}
  WordPress:
    name: WordPress
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: ${VOLUME_WORDPRESS_PATH}

